#define which apparatuses are on which page

apparatuses:
  vault:
    start page:
      nl: 2
      en: 61
    end page:
      nl: 13
      en: 70
    group:
      1: acrobatic
      2: acrobatic
      3: acrobatic
      4: acrobatic
      5: acrobatic
      0: acrobatic
    regex:
      group:
        en: GROUP\s+(\d).*?([A-Z].*?)\sVT
        nl: GROEP\s+(\d).*?([A-Z].*?)\d\.\d{2}
      element:
        en: (T?\d\.\d+?)\s+(?!TOEGEVOEGD?)(?!T\d\.\d+)([^\d \ ].+?)\s*(\d\.\d*)\s*P
        nl: (T?\d\.\d+?)\s+(?!TOEGEVOEGD?)(?!T\d\.\d+)([^\d \ ].+?)\s*(\d\.\d*)\s*P
  uneven bars:
    start page:
      nl: 15
      en: 73
    end page:
      nl: 53
      en: 105
    group types:
      1: acrobatic
      2: acrobatic
      3: acrobatic
      4: acrobatic
      5: acrobatic
      6: acrobatic
    regex:
      group:
        en: (\d\.000).*?([A-Z]+.*)\sUB
        nl: (\d\.000).*?([A-Z]+.*)\sA\sB\sC
      element:
        en: (\d+\.\d+)\s+(?!(?:UB|\d\.\d{3,}s|-|–|ʊ|\s|\.|\/))(.*?)(?=\s+\d+\.\d+|$|\s{8,})
        nl: (\d+\.\d+)\s+(?!(?:Brug|\d\.\d{3,}|\s|\.|\/))(.*?)(?=\s+\d+\.\d+|$|\s{8,})
  beam:
    start page:
      nl: 55
      en: 108
    end page:
      nl: 92
      en: 146
    group types:
      1: acrobatic
      2: gymnastic
      3: gymnastic
      4: acrobatic
      5: acrobatic
      6: acrobatic
    regex:
      group:
        en: (\d\.000).*?([A-Z]+.*)\sBB
        nl: (\d\.000).*?([A-Z]+.*)\sA\sB\sC
      element:
        en: (\d+\.\d+)\s+(?!(?:BB|\d\.\d{3,}|\s|-|–|ʊ|\.|\/|\[A-Z]{5,}))(.*?)(?=\s+\d+\.\d+|$|\s{8,})
        nl: (\d+\.\d+)\s+(?!(?:Balk|\d\.\d{3,}|\s|-|–|\.|\/|\[A-Z]{5,}))(.*?)(?=\s+\d+\.\d+|$|\s{8,})
  floor:
    start page:
      nl: 100
      en: 148
    end page:
      nl: 126
      en: 168
    group types:
      1: gymnastic
      2: gymnastic
      3: acrobatic
      4: acrobatic
      5: acrobatic
      6: gymnastic
    regex:
      group:
        en: (\d\.000).*?([A-Z]+.*)\sFX
        nl: (\d\.000).*?([A-Z]+.*)\sA\sB\sC
      element:
        en: (\d+\.\d+)\s+(?!(?:FX|\d\.\d{3,}|\s|\.|\/))(.*?)(?=\s+\d+\.\d+|$|\s{4,})
        nl: (\d+\.\d+)\s+(?!(?:Vloer|\d\.\d{3,}|\s|\.|\/))(.*?)(?=\s+\d+\.\d+|$|\s{4,})
file:
  en: source/files/women/en_2022-2024 WAG COP.pdf
  nl: source/files/women/NTS-Elemententabel-2022-2024-deel-4-versie-01-07-22.pdf
language_description_index:
  en: 0
  nl: 0
element_grouping_file: source/element_grouping.yaml
output directory: src/lib/data/elements/women/
string adjustments:
  - ["  ", " "]
  - ["    ", " "]
  - ["   ", " "]
  - [" ’", "’"]
  - [" '", "'"]
  - ["ME T", "MET"]
  - ["MET /", "MET/"]
  - ["MET/ ", "MET/"]
  - ["FLIK -FLAK", "FLIK-FLAK"]
  - ["LA -DRAAI", "LA-DRAAI"]
  - ["L ENGTE AS-DRAAI", "LA-DRAAI"]
  - ["VOO ROVER", "VOOROVER"]
  - ["MO8N7S", "MOUNTS"]
  - ["ʊ", "-"]
  - ["G,A17 C,5C/E6", "GIANT CIRCLES"]
  - [")/,*+7", "5.000 - ACROBATIC FLIGHT"]
