#define which apparatuses are on which page

apparatuses:
  - vault
  - uneven bars
  - beam
  - floor
FIG: NTS-Elemententabel-2022-2024-deel-4-versie-01-07-22.pdf
output_directory: ../data/
pages:
  vault:
    start: 3
    end: 13
  uneven bars:
    start: 15
    end: 47
  uneven bars TA:
    start: 49
    end: 53
  beam:
    start: 55
    end: 92
  beam TA:
    start: 94
    end: 99
  floor:
    start: 101
    end: 120
  floor TA:
    start: 122
    end: 126
