#define which apparatuses are on which page

apparatuses:
  floor:
    start page:
      nl: 39
      en: 43
      fr: 43
      es: 43
    end page:
      nl: 50
      en: 53
      fr: 53
      es: 53
    group types:
      1: non-acrobatic
      2: acrobatic
      3: acrobatic
    regex:
      group:
        en: EG\s*([IV]*):\s*(.*?)\s*(?=\d+\.|\Z)
        fr: EG\s*([IV]*):\s*(.*?)\s*(?=\d+\.|\Z)
        es: EG\s*([IV]*):\s*(.*?)\s*(?=\d+\.|\Z)
        nl: EG\s*([IV]*):\s*(.*?)\s*(?=\d+\.|\Z)
      element:
        en: (\d+)\.\s+(.*?)\s*(?=\|\d+\.|\Z)
        fr: (\d+)\.\s+(.*?)\s*(?=\|\d+\.|\Z)
        es: (\d+)\.\s+(.*?)\s*(?=\|\d+\.|\Z)
        nl: (\d+)\.\s+(.*?)\s*(?=\d+\.|\Z)
  pommel horse:
    start page:
      nl: 63
      en: 66
      fr: 66
      es: 66
    end page:
      nl: 76
      en: 77
      fr: 77
      es: 77
    group types:
      1: acrobatic
      2: acrobatic
      3: acrobatic
      4: acrobatic
    regex:
      group:
        en: EG\s*([IV]*):\s*(.*?)\s*(?=\d+\.|\Z)
        fr: EG\s*([IV]*):\s*(.*?)\s*(?=\d+\.|\Z)
        es: EG\s*([IV]*):\s*(.*?)\s*(?=\d+\.|\Z)
        nl: EG\s*([IV]*):\s*(.*?)\s*(?=\d+\.|\Z)
      element:
        en: (\d+)\.\s+(.*?)\s*(?=\|\d+\.|\Z)
        fr: (\d+)\.\s+(.*?)\s*(?=\|\d+\.|\Z)
        es: (\d+)\.\s+(.*?)\s*(?=\|\d+\.|\Z)
        nl: (\d+)\.\s+(.*?)\s*(?=\d+\.|\Z)
  rings:
    start page:
      nl: 83
      en: 85
      fr: 85
      es: 85
    end page:
      nl: 102
      en: 101
      fr: 101
      es: 101
    group types:
      1: acrobatic
      2: acrobatic
      3: acrobatic
      4: acrobatic
    regex:
      group:
        en: EG\s*([IV]*):?\s*(.*?)\s*(?=\d+\.|\Z)
        fr: EG\s*([IV]*):?\s*(.*?)\s*(?=\d+\.|\Z)
        es: EG\s*([IV]*):?\s*(.*?)\s*(?=\d+\.|\Z)
        nl: EG\s*([IV]*):?\s*(.*?)\s*(?=\d+\.|\Z)
      element:
        en: (\d+)\.\s+(.*?)\s*(?=\|\d+\.|\Z)
        fr: (\d+)\.\s+(.*?)\s*(?=\|\d+\.|\Z)
        es: (\d+)\.\s+(.*?)\s*(?=\|\d+\.|\Z)
        nl: (\d+)\.\s+(.*?)\s*(?=\d+\.|\Z)
  vault:
    start page:
      nl: 109
      en: 108
      fr: 108
      es: 108
    end page:
      nl: 116
      en: 115
      fr: 115
      es: 115
    group types:
      1: gymnastic
      2: gymnastic
      3: acrobatic
      4: acrobatic
      5: acrobatic
      6: gymnastic
    regex:
      group:
        en: EG\s*([IV]*):\s*(.*?)\s*(?=\d+\.|\Z)
        fr: EG\s*([IV]*):\s*(.*?)\s*(?=\d+\.|\Z)
        es: EG\s*([IV]*):\s*(.*?)\s*(?=\d+\.|\Z)
        nl: EG\s*([IV]*):\s*(.*?)\s*(?=\d+\.|\Z)
      element:
        en: (\d{3})\.\s?\|?(?!\s|\|)([^\d|\(].+?)\s*(?=\|\d+\.|\Z)
        fr: (\d{3})\.\s?\|?(?!\s|\|)([^\d|\(].+?)\s*(?=\|\d+\.|\Z)
        es: (\d{3})\.\s?\|?(?!\s|\|)([^\d|\(].+?)\s*(?=\|\d+\.|\Z)
        nl: (\d{3})\.\s?\|?(?!\s|\|)([^\d|\(].+?)\s*(?=\|\d+\.|\Z)
  parallel bars:
    start page:
      nl: 123
      en: 122
      fr: 122
      es: 122
    end page:
      nl: 140
      en: 137
      fr: 137
      es: 137
    group types:
      1: gymnastic
      2: gymnastic
      3: acrobatic
      4: acrobatic
      5: acrobatic
      6: gymnastic
    regex:
      group:
        en: EG\s*([IV]*):\s*(.*?)\s*(?=\d+\.|\Z)
        fr: EG\s*([IV]*):\s*(.*?)\s*(?=\d+\.|\Z)
        es: EG\s*([IV]*):\s*(.*?)\s*(?=\d+\.|\Z)
        nl: EG\s*([IV]*):\s*(.*?)\s*(?=\d+\.|\Z)
      element:
        en: (\d+)\.\s+(.*?)\s*(?=\|\d+\.|\Z)
        fr: (\d+)\.\s+(.*?)\s*(?=\|\d+\.|\Z)
        es: (\d+)\.\s+(.*?)\s*(?=\|\d+\.|\Z)
        nl: (\d+)\.\s+(.*?)\s*(?=\|\d+\.|\Z)
  high bar:
    start page:
      nl: 147
      en: 145
      fr: 145
      es: 145
    end page:
      nl: 165
      en: 161
      fr: 161
      es: 161
    group types:
      1: acrobatic
      2: acrobatic
      3: acrobatic
      4: acrobatic
    regex:
      group:
        en: EG\s*([IV]*):\s*(.*?)\s*(?=\d+\.|\Z)
        fr: EG\s*([IV]*):\s*(.*?)\s*(?=\d+\.|\Z)
        es: EG\s*([IV]*):\s*(.*?)\s*(?=\d+\.|\Z)
        nl: EG\s*([IV]*):\s*(.*?)\s*(?=\d+\.|\Z)
      element:
        en: (\d+)\.\s+(.*?)\s*(?=\|\d+\.|\Z)
        fr: (\d+)\.\s+(.*?)\s*(?=\|\d+\.|\Z)
        es: (\d+)\.\s+(.*?)\s*(?=\|\d+\.|\Z)
        nl: (\d+)\.\s+(.*?)\s*(?=\d+\.|\Z)
file:
  en: source/files/Men/en_ 2022-2024 MAG CoP.pdf
  fr: source/files/Men/en_ 2022-2024 MAG CoP.pdf
  es: source/files/Men/en_ 2022-2024 MAG CoP.pdf
  nl: source/files/Men/Reglement-Bovenbouw-versie-1.1.pdf
exception_file: source/files/Men/elements_men_G_H.yaml
vault_values_file: source/files/Men/vault_values.yaml
output directory: data/elements/men/
string adjustments:
  - ["  ", " "]
  - ["    ", " "]
  - ["   ", " "]
  - [" ’", "’"]
  - [" '", "'"]
  - ["ME T", "MET"]
  - ["MET /", "MET/"]
  - ["MET/ ", "MET/"]
  - ["FLIK -FLAK", "FLIK-FLAK"]
  - ["LA -DRAAI", "LA-DRAAI"]
  - ["L ENGTE AS-DRAAI", "LA-DRAAI"]
  - ["VOO ROVER", "VOOROVER"]
  - ["MO8N7S", "MOUNTS"]
  - ["ʊ", "-"]
  - ["G,A17 C,5C/E6", "GIANT CIRCLES"]
